---
title: "Economy of music in Europe: Novel data collection methods and indicator"
subtitle: "DOI: 10.5281/zenodo.6435322"
author:
- Daniel Antal, CFA, Reprex & University of Amsterdam
- Andrés García Molina, PhD, Reprex
date: "`r Sys.Date()`"
output:
  html_document: default
  pdf_document: default
  word_document: default
bibliography:
- datascience.bib
- mme.bib
- legalccsi.bib
- antal.bib
- competition.bib
- caselaw.bib
- dcms.bib
- digitalmusicobservatory.bib
- packages.bib
- musicindustry.bib
- musicology.bib
- statisticalmethodology.bib
- datainteroperability.bib
- eulaw.bib
- openscience.bib
- opa.bib
- opendata.bib
- rpackages.bib
- valuation.bib
- valuegap.bib
---

```{r setupdmoeconomypillar, include=FALSE}
knitr::opts_chunk$set(echo=FALSE, message=FALSE, warning=FALSE, out.width = '95%', fig.align = 'center')
library(knitr)
library(here)
here::here()
```

## Abstract

In the last decade, the evidence-based policy movement gained significant traction in Europe as well as globally. Its focus has been to increase the rigour of the evidence generated, to improve the credibility and understandability of evidence created for policy purposes.  As evidence-based policies often rely on scientific evidence, the evidence-based policy movement went hand in hand with the efforts to increase the transparency and reproducibility of scientific research (See: [@manifesto_for_reproducible_science_2017] and in an EU context [@JRC99722; @reproducibility_scientific_results_eu_2020; @progress_open_science_2020].)  

Our policy tools will make possible the first, large scale European application of the Open Policy Analysis, which grew out from several initiatives in research transparency, such as the Berkeley Initiative for Transparency in the Social Sciences, the Data Access and Research Transparency (DA-RT) group, the Center for Open Science and their TOP Guideline, the Meta-Research Innovation Center at Stanford University. Globally, the World Bank promotes this framework [@framework_for_opa_2020; @acre_guide] and they are fully in line with the Open Science objectives of the European Union 
[@reproducibility_scientific_results_eu_2020]. For further details please refer to \@ref(methodology-opa) [Methodology for policy context, pilot studies, and impact pathways](#methodology-opa)

Following the state-of-the-art in reproducible, open policy analysis, we will introduce the "live policy document" developed by Reprex in cooperation with IVIR (in science), and Artisjus and SOZA (in music industry application.). This will follow the highest level or reproducability of transferability. The valuation report on Bulgarian music will be contained in a clearly documented dynamic document that contains the assumptions, software code to read in the data from the data sources, perform the modelling, create the visualizations, document citations, and place it in the same file with the conclusions.   Our "live policy documents" with a press of a button are reading in new information, change model outputs and visualizations, update the bibliography, create an html, PDF, ebook and docx output, and place the results on the Zenodo open science repository with an authoritative copy and DOI.  Change the data input from Bulgaria to Belgium, and re-interpret the model results, tables, visualization in the document, you get a scientifically valid valuation for Belgium.

## Methodology

## References
