---
title: "Report on the European Music Economy"
subtitle: "DOI: 10.5281/zenodo.6464782"
author:
- Daniel Antal, CFA, Reprex & University of Amsterdam
- Poort, Joost, PhD, University of Amsterdam
- Botazzi, Guilio, PhD, University of Pisa
date: "`r Sys.Date()`"
output:
  md_document: default
  pdf_document: default
  word_document: default
  html_document: default
bibliography:
- datascience.bib
- mme.bib
- legalccsi.bib
- antal.bib
- competition.bib
- caselaw.bib
- dcms.bib
- digitalmusicobservatory.bib
- packages.bib
- musicindustry.bib
- musicology.bib
- statisticalmethodology.bib
- datainteroperability.bib
- eulaw.bib
- openscience.bib
- opa.bib
- opendata.bib
- rpackages.bib
- valuation.bib
- valuegap.bib
---

```{r setupdmoeconomypillar, include=FALSE}
knitr::opts_chunk$set(echo=FALSE, message=FALSE, warning=FALSE, out.width = '95%', fig.align = 'center')
library(knitr)
library(here)
here::here()
```

## Abstract

In the last decade, the evidence-based policy movement gained significant traction in Europe as well as globally. Its focus has been to increase the rigour of the evidence generated, to improve the credibility and understandability of evidence created for policy purposes.  As evidence-based policies often rely on scientific evidence, the evidence-based policy movement went hand in hand with the efforts to increase the transparency and reproducibility of scientific research (See: [@manifesto_for_reproducible_science_2017] and in an EU context [@JRC99722; @reproducibility_scientific_results_eu_2020; @progress_open_science_2020].)  

Our [Report on the European Music Economy](https://zenodo.org/record/6464782#.Ylq7JNpBzIU), and its supporting document, [Economy of music in Europe: Novel data collection methods and indicators]() will follow the Open Policy Analysis Guidelines and the best practices of the European Union's Knowledge For Policy and the [European Open Science Cloud](https://eosc-portal.eu/) portal. 

The current version of the _Report on the European Music Economy [outline]_ is a research planning document that sets out our 9 transparancy criteria following the best practices (Level 3) of the Open Policy Analysis Guidelines, and provides some illustrations on how a "live policy document" works with a few reproducible datasets^[Report on the European Music Economy [outline] [@report_european_music_economy]]. If our Proposal is successful and gets funded, the document will start to contain reused data from 2023, new data from 2024, and can be first read as draft policy document in the summer of 2024. 


## Open Output 

1. **Ensure unified output by defining the most appropriate format for the report
before publishing, and justifying changes to format output across reports.** Best practice: A detailed description of output is provided, including a sample output published 
pre-release of final results, using version control within and across reports

2. **Establish a clear link between input and output by displaying how the output changes under different assumptions**. Best practice: An interactive tool allowing for adjusted inputs is provided, and its underlying code shares the same key sections of code behind the analysis section.


## Open Materials 

3. **Provide clear accounts of all methodological procedures in a way that is easily interpreted by an informed reader.** Code is clearly documented into a dynamic document, or
open notebook. No spreadsheets. Our Methodologies are part of our Proposal, and they can be fined as dynamic document on the Github repo [github.com/dataobservatory-eu/report-european-music-economy](https://github.com/dataobservatory-eu/report-european-music-economy), and versions with metadata and DOI of the methodology document on the Zenodo open science repository under the title [Digital Music Observatory](https://zenodo.org/communities/music_observatory/). 

4. **Share raw (or analytic) data and materials in a way that the analysis is reproducible with minimal effort.**

5. **Share an open report that includes clear accounts of all methodological procedures, data, and assumptions.** Best practice: All project components are organized in a selfcontained folder using a Standard File Structure (SFS), and a readme file is included. We place all files with SFS on the European open science repository Zenodo on [zenodo.org/communities/music_observatory/](https://zenodo.org/communities/music_observatory/).

7. **Label and document each input, including data, research, and guesswork.** Best practice: List all inputs, their sources, and provide links or detailed references. We use DublinCore and DataCite mandatory and recommended descriptive metadata to provide not only full bibliographic reference, but also full findability and interoperabilty, and clear reuse conditions.

7. **Ensure that code/spreadsheets are reproducible**. Best practice: For code: Code is easily readable and possible to run with just one click. Spreadsheets are published with the code, and the code re-creates the spreadsheet from the latest data on one click. New runs are placed in the Digital Music Observatory community space on Zenodo, like []().

9. **Use a version control strategy.** Best practice: All team members use version control software and track changes in a shared project repository. This document is placed in a version controlled repostiory [github.com/dataobservatory-eu/report-european-music-economy](https://github.com/dataobservatory-eu/report-european-music-economy)



Following the state-of-the-art in reproducible, open policy analysis, we will introduce the "live policy document" developed by Reprex in cooperation with IVIR (in science), and Artisjus and SOZA (in music industry application.). This will follow the highest level or reproducability of transferability. The valuation report on Bulgarian music will be contained in a clearly documented dynamic document that contains the assumptions, software code to read in the data from the data sources, perform the modelling, create the visualizations, document citations, and place it in the same file with the conclusions.   Our "live policy documents" with a press of a button are reading in new information, change model outputs and visualizations, update the bibliography, create an html, PDF, ebook and docx output, and place the results on the Zenodo open science repository with an authoritative copy and DOI.  Change the data input from Bulgaria to Belgium, and re-interpret the model results, tables, visualization in the document, you get a scientifically valid valuation for Belgium.
