---
title: "section1"
author: "Daniel Antal, CFA"
date: "`r Sys.Date()`"
output:
  html_document: default
  pdf_document: default
  word_document: default
bibliography:
- datascience.bib
- mme.bib
- legalccsi.bib
- antal.bib
- competition.bib
- caselaw.bib
- dcms.bib
- digitalmusicobservatory.bib
- packages.bib
- musicindustry.bib
- musicology.bib
- statisticalmethodology.bib
- datainteroperability.bib
- eulaw.bib
- openscience.bib
- opa.bib
- opendata.bib
- rpackages.bib
- valuation.bib
- valuegap.bib
---

The music industry has fundamentally changed in the past decade in two ways.  These changes not only did not contribute to its long-term financial sustainability, but did not make enough effort to promote environmental, social and governance sustainability. First, after decades of leadership from the recorded music industry, live music became the main breadwinner of most artists.  As we have seen in xxxxx, xxx-xxxx of the income of music creators was connected to this source of income before the pandemic.  The Covid-19 epidemic brought this questionably sustainable market structure to a halt.  The recorded music business (with its publishing side, and the recording side that is often further divided by producers’ and performer’s shares) was not able to balance out of this shortfall.  The reason for this problem is that after the piracy and technology induced collapse of the recorded industry around 2001, the slowly emerging new business model based on the micropayments of various streams did not replace the lost value from the traditional mechanical licensing (digital downloads and physical sales) and public performance (radio, television, background music) sales. In the biggest European music market, in the United Kingdom, the failure of the streaming model already induced a parliamentary and policy review.  

Although the call asks it as a question, or data suggests for a fact that streaming and other royalty sources had not been able to replace the lost live music revenues in any European markets. Live music revenues had been at least 50% of all artists revenues in mature markets, and up to 90% in emerging market, while streaming has accounted for up to 25% in mature markets and only a few percent in emerging markets. Our WP Music Economics has the ambition to create pathways to measure this problem, and offer new valuation methodologies that allow the stakeholders to achieve a healhier income mix. This is all the more important because streaming growth before and during the pandemic had been unequal, and while important music centers of the world had seen a replacement of their pre-internet revenues, most segments of the European recorded industry had never truly participated in this growth.


In streaming, music industry organizations and companies only report revenues (total streaming revenue for Sweden, or in some cases, average monthly revenue for a country), which, as we have shown in the report to the UK Intellectual Property Office, obscures the changes of streaming price movements, streaming quantities, exchange rate changes and currency translation weights, and monthly accruals. If an Italian label with an emerging artist receives 15% more euros in June than in May, currently, there is no way to know if a) there artist was doing better b) it was played in markets where the per stream rate is higher c) it received accrued income from some export markets that had been growing since February d) the artists was played in Japan and the euro rate changed favorable to the label. 

Even if we do not have the institutional and legal strenght of an official statistical agency, and cannot rely on mandatory surveying or certain more institutionalized quality control measures, we want to turn balance them out with our strength: relying on the quality control of the scientific community and the open-source software/algorithm development community, and the flexibility of working with voluntary and well-targetted data collection in select countries and segments. To do this, we rely on the best methodologies developed first in the United States, 

Behind the profound changes of the music industry lies its ability to absorb technological and business innovation, and to apply to challenges posed by mass piracy, or the Covid-19 pandemic with new business models.  New technological innovations like micropayments and personalized targetting in streaming, NFT/Blockchain or AI (that is not only present in curating streaming, but increasingly in the programming of festivals or radios) rely on the correct use of information technology. However, without metadata, data is only potential information. In the past years, our Consortium members have been involved in various R&D and scentific projects to understandt the causes of low metadata quality, its consequences, and various open-source and propriatary ways to match centralized metadataystems with a decentralized way of improving them.

Our policy tools will make possible the first, large scale European application of the Open Policy Analysis, which grew out from several initiatives in research transparency, such as the Berkeley Initiative for Transparency in the Social Sciences, the Data Access and Research Transparency (DA-RT) group, the Center for Open Science and their TOP Guideline, the Meta-Research Innovation Center at Stanford University. Globally, the World Bank promotes this framework [@framework_for_opa_2020; @acre_guide] and they are fully in line with the Open Science objectives of the European Union 
[@reproducibility_scientific_results_eu_2020]. For further details please refer to \@ref(methodology-opa) [Methodology for policy context, pilot studies, and impact pathways](#methodology-opa)

Our Consortium aims to implement [Open Policy Analysis Guidelines](http://www.bitss.org/wp-content/uploads/2019/03/OPA-Guidelines.pdf), which grew out from several initiatives in research transparency, such as the Berkeley Initiative for Transparency in the Social Sciences, the Data Access and Research Transparency (DA-RT) group, the Center for Open Science and their TOP Guideline, the Meta-Research Innovation Center at Stanford University [@opa_guidelines; @OPA_guardia_et_al_2020]. The OPA Guidelines give practical guidance on how to improve the transparency, replicability, and as a result, the reusability of the policy-making work with a scientific underpinning. (See [WP Open Dissemination - OPA](#WP-OPA).)

## 1.1	Objectives and ambition 
The project’s scoping aim is to create an open, scalable data-to-policy pipeline for European music ecosystems. This aim entails three distinct objectives, which connect to the three phases of the project execution: 
- O1. Map the data landscape will be accomplished in the first set of tasks (T1.1, T2.1, T3.1, T4.1)
- O2. Bridge data gaps will be accomplished in the second set of tasks (T1.2, T2.2, T3.2, T4.2)
- O3. Empower stakeholders to take data-driven actions will be accomplished in the third set of tasks (T1.3, T2.3, T3.3, T4.3)
Each objective will be realised across four work packages targeting the four pillars of the Feasibility study for the establishment of a European Music Observatory: WP1. Economy of music in Europe; WP2. Music diversity and circulation; WP3. Music, society, and citizenship; and WP4. Innovation and future trends. The project’s innovations will be amplified through the project management and implementation work packages (WP5 & 6). The objectives are designed to advance the state of the art with regard to data collection, policymaking, and business practices in the music industry. Both the objectives and the outputs will be optimised for transferability to other cultural and creative industries.
O1. MAP the data landscape. The project will identify extant and potential data sources, specify appropriate data collection methods, and develop policy-relevant indicators that capture the significance of the data at hand. Objective 1 meets the expected outcomes of providing new/improved methodologies for measuring the value of music and developing indicators to represent this value. It will be realised in T1.1, T2.1, T3.1, and T4.1, and reported in D1.1, D2.1, D3.1, and D4.1.

For readability, we start with the end-user objectives that we describe in greater detail, and then we show our intermediate objectives that will take us to the desired policy outcomes. 

## O3 Empower stakeholders to take data-driven actions will be accomplished in the third set of tasks

STATE OF THE ART – 1 paragraph each on economy of music in Europe; music diversity and circulation; music, society, and citizenship; and innovation and future trends.
AMBITION – 0.5 page – “preview” of the relevant methods and impacts

The gradual transition of the music economy from the mechanical licensing and public performance model to the streaming model has two unfavourable outcomes.  Streaming revenues in most market segments (independent artists, emerging national markets) have never replaced the lost mechanical licensing and public performance revenues---streaming often reduced the market shares of local stakeholders and let to an unprecedented concentration of revenues in the hands of few (and usually non-European) artists and labels. Second, this lead to an over-reliance on live music revenues, particularly in the emerging and future markets of Europe. This model turned out to be not sustainable when an external shock, Covid-19 pandemic forced live performances to halt. 

Our ambition is to adjust all the existing intellectual property valuation models that were earlier recognized for music valuation to the new business models and realities of a streaming-based recorded music industry. From an economics point of view, this means adjusting valuation models to account for zero-price platforms. In music economics, the greatest amount of consumer use has a zero price, either because of an unlicensed use, or because somebody else (for example, a radio station or a freemium streaming platform) pays for the use. When the user does not pay, there is no market transaction and accounting trail---practically neither the quantity of the use or the price of the use, the two most important variables of any economics model, is available with certainty. In fact, the zero-price platform model, which is often analysed with examples of AirBnB, LinkedIn, Facebook, or Youtube, is a very important problem in current competition economics and intellectual property economics and generally thought to be originating from the music industry itself.  Commercial radio, and later commercial and music television were the first pioneers of a model where users do not pay for music but listen to commercials instead. We will use statistical techniques to estimate both harmonised quantities and shadow prices on zero-price platforms. We will borrow techniques from advanced financial economics to bring price transparency into streaming.

In music policy, diversity and the maintenance of a healthy audience and market share for the local, national and European works/recordings and artists had always been an important cultural policy goal. In the centralised curation model and regulation of radio and television---where a music editor chose the music for everybody---had its policy toolkits. Until the 1990s most broadcasters were state-owned and the state as an owner set targets for them. With the increase of commercial radio, then television, local content regulation forced broadcasters to maintain enough airspace for local content. Strengthened by education policies in music appreciation they helped local music sales through discovery. Our WP Diversity develops toolkits that work in streaming, too, where most curation is taken over by autonomous (AI-driven systems), playlisting is decentralised, and often fully personalised. Touching on the state of the art in applied musicology, xxxxxx.  The overlap with our economics toolkit is not coincidental: a higher visibility of independent, small-country or European repertoires in live and recorded performance, or streaming in economics terms means a higher competitiveness or higher market share. While the data-driven action may be different for a cultural policymaker than for a royalty valuator, the underlying data about use, value and market share is in many cases the same. 

Our Music, society, and citizenship work package can be seen as a supporting policy toolkit for improving the economic value, the diversity and competitiveness of xxxxx.  It is centred around making use of the quantitative cultural sociology model of cultural (music) participation.  Measuring participation is necessarily broader than measuring consumption. Consumption is a market category, and usually entails sales transactions and an accounting trail. As most music use (at least in enjoyment hours) is free, and so are many forms of active participation (amateur playing and singing, and informal learning practices; liturgical use music), quantitative surveys must be used that can be harmonised with existing survey programs (such as Eurobarometer, EU-SILC, and AES) and also with the existing transactional databases of music (about radio/television licensing or ticket sales.)

The European music industry is dominated by freelancers, micro and small enterprises, yet it must apply technological and business innovation to business challenges posed by global data monopolies on platforms that it uses for selling music, or the Covid-19 pandemic that disrupted the live music part of the ecosystem. The new information systems rely on metadata to put data into work and build useful information out of it. This metadata, often called 'data about data' is central to make NFT/blockchain or autonomous AI systems work in a reliable, trustworthy, and ethical manner. This metadata is the focus point of our innovation toolkit, because without proper metadata, modern music technology will not work for, but against the European creators. 


### O1. Map the data landscape will be accomplished in the first set of tasks (T1.1, T2.1, T3.1, T4.1)

In the last decade, the evidence-based policy movement gained significant traction in Europe as well as globally. Its focus has been to increase the rigour of the evidence generated, to improve the credibility and understandability of evidence created for policy purposes.  As evidence-based policies often rely on scientific evidence, the evidence-based policy movement went hand in hand with the efforts to increase the transparency and reproducibility of scientific research (See: [@manifesto_for_reproducible_science_2017] and in an EU context [@JRC99722; @reproducibility_scientific_results_eu_2020; @progress_open_science_2020].)  


We will use an interdisciplinary methodology of economics, royalty accounting, quantiative finance, and socio-economic research in copyrights and blockchain for achieving the goals in WP1, WP4, and partly WP3.  The goals of WP2 will include socio-legal research and quantiative musicology, and WP3 quantiative music sociology.  All WPs will deliver data via WP5 that uses reproducible scientific and policy research supported by data science and computer science.

In our work, we will improve several quantitative methodologies used in music copyright data management and cultural statistics, among others, to produce improved indicators for business, policy, and academic use. Throughout the project, we will follow the Eurostat guidelines on creating new indicators [@eurostat_harmonised_indicators_2014; @angelova-tosheva_methodological_2019; @eurostat_guide_2018], which will ensure broad consensus-forming among stakeholders around the objectives and methodology of the improved measurements. We will create key business indicators (for individual companies), city-, regional-, nationalü and pan-European/EU indicators, but focus on the national level, because cultural policy and creative industry policy is at this level in the EU subsidiarity setting. Because the Slovak Republic is currently developing a detailed policy indicator set where SOZA is providing indicators, and EUBA's researchers place scientific input, we will place an emphasis on this country, as we are most likely to get the widest level of business and policy user feedback. We will practically use the production side statistics, following xxxxx 

Our ambition is to fill the data gaps with data that is created with similar methodology, user testing, quality control, documentation and dissemination standards that Eurostat or national statistical offices do, and balance the legal of legal mandates and large institutional capacity with relying on the quality control of the scientific community and the open-source software/algorithm development community, and the flexibility of working with voluntary and well-targetted data collection in select countries and segments. To do this, we rely on the best methodologies developed first in the United States, then implemented on EU and at last on national levels

Our consortium has a very strong background in economics and quantiative finance, and experience with royalty accounting and valuation, with much prior experience in putting this into scientific, business and policy use. Our focus will be on methodological difficulties that we have been presented in our researchers work in the past years. Our first focus is to modify the existing valuation models of the recorded industry, and intellectual property in general, with the increasing use of the so-called zero-price platforms, like YouTube, Facebook, radio, unlicensed copying, torrenting, where people do not pay directly for music. Our Consortium Members have gradually extended the music comparators model xxxx, and created econometric models that followed the evolving jurisprudence of the Court of the European Union^[The jurisprudence of the Court of the European Union, particularly _OSA v Léčebné lázně Mariánské Lázně_ [@cjeu_osa_2014] and _AKKA/LAA vs Konkurences padome_ [@cjeu_akka_2017] must be considered when making market comparisons, respecting the agreement made closing the _Commission v CISAC_ case [@infocuria_cisac_v_commission_2013].]. we aim to standardize this method, using mapping xxxx, and transfering and improving the Hungarian/Slovak model to Bulgaria in a way that can be replicated in any European country.

To go back to our previous example, if an Italian label with an emerging artist receives 15% more euros in June than in May, currently, there is no way to know if a) there artist was doing better b) it was played in markets where the per stream rate is higher c) it received accrued income from some export markets that had been growing since February d) the artists was played in Japan and the euro rate changed favorable to the label. The currently available market information (annual or monthly total or average revenue) is not useful, because streaming revenues are extremely skewed---rendering average or median values useless to represent a 'typical' Italian song, artist, or label.  

## O2. BRIDGE data gaps. 

The project will collect data from multiple sources using appropriate methods, create synthetic datasets capable of populating the project indicators, and visualise and report the data collected. Objective 2 meets the expected outcomes of promoting standardised data collection on the contributions of music to the economy and estimating its impact on society. It will be realised in T1.2, T2.2, T3.2, and T4.2, and reported in real-time via the Digital Music Observatory (D5.1).

We will use the standard mapping of the music industry^[The standard mapping of the music industry was developed in the US ([@hull_music_2011], and was adopted by the _Joint Research Centre Institute for Prospective Technological Studies_ [@leurdijk_statistical_music_2012]). Artisjus and its neighboring rights societies created a more granual report in Hungary and Slovakia [@antal_proart_2015; @antal_slovenskom_hudobnom_2019_en], and a special version for focusing on the unlicensed, "free" use of music in Croatia [@antal_pcr_croatia_2019], and eventually the comparative report to finish the original mission statement of the CEEMID project .] to identify the configuration of the music industry, and place critical information gathering points where value is added, jobs are created in the conversion chain of music use to industry (artist) revenue. 

The working group of ESSnet-Culture has summarized the best practices in cultural statistics and xxx, that our Consoritum members have been following for 8 years. The most important takeaway is that in cases where official statistical offices have no clear mandate or resource to collect data (microenterprises) or to process existing data with traditional methodology (data products made for example from Eurobarometer, EU-SILC, AES, anonymized tax filings, data from inflation measurement surveys), and even with the recent improvement efforts both in terms of methodology and statistical regulation, the situation will not significantly improve. The only way to seriously imporove data availability in the music industry is to apply standard statistical procedures in a _voluntary_ way with a joint effort from cultural policy organizations and representative industry organizations.


# Methodology 

## Meh

## Methodology O2

Even taking into consideration to recent efforts to improve the regulation and methodology of the coverage of the Artst, entertainment and recreation services part of the harmonized Structural Business Statistics^[See [@eurostat_sbs_manual_2021]]


[@selectivity_big_data_2018]



## Methodology

We present the methodology in time-sequence, and differently from the actual outcomes for readability. 


In the past years, there has been an increased interest in analysing online platforms where consumers do not pay a price. Watching a music video on YouTube, reading amusing content on Facebook, or finding accommodation on AirBnB does not cost oney for the buyer. The buyer is however committed to viewing advertisements, give up her data. In a monetary sense, a  commission from a two-sided product (the supply side of a rented room) offers compensation for the platform. As many analysts remarked, such practices probably originated from the use of music and audiovisual content on radio and television [@cma_online_platforms_advertising_2020, pp 44--45; @support_study_commission_2021]. Most recorded music use takes place without the user paying for fit.



modifying the . 


The **market approach** tries to identify a payment rate, regardless of if it is made in lump sum, monthly or annually to established, sufficiently similar uses. Many ideas were tried internationally to identify the sufficiently similar use of music streaming; for example, relating ad-supported and automatically selected songs to radio streams, and relating cases where the user controls the selection of songs, and may even download them to music downloads.  We have used in several cases *econometric comparisons* using datasets (availabe for their members only) by IFPI and CISAC^[CISAC offers very different kind of data, because since the _Commission v CISAC_ case [@infocuria_cisac_v_commission_2013] it refrains from directly helping its members price-setting.  CISAC’s key performance indicator is the revenue connected to a certain right, which can be used as a basic of calculating shadow prices.]Our econometric models follow apply both equitable remuneration and fair valuation principles, and similar principles of competition law^[The jurisprudence of the Court of the European Union, particularly _OSA v Léčebné lázně Mariánské Lázně_ [@cjeu_osa_2014] and _AKKA/LAA vs Konkurences padome_ [@cjeu_akka_2017] must be considered when making market comparisons.]. Our **market comparators model**, which has been used to for both mechancial and public performance valuations, particularly radio rights, UUG platforms, and private copying. The challenge of valuing music in these contexts, including monitoring the value gap, is the correct estimation of quantities and shadow prices.

We will rely on the expertise 



Even though the economic objectives of intellectual rights and copyright policy, or the general employment and value-added goals of music economics seem relatively distant from cultural diversity policy goals, on the level of the data landscape, we see some overlap with music economics. When we try to understand the quantity or market share of Slovak songs in in Slovak radio or Czech radio, or the Swedish songs in Sweden or Italy, we are in fact asking what economists would frame in the context of national, label, or artist competitiveness. For the calculations, we need the same quantities and prices as in economics. 